name: TownyBlockBugFix
version: '${project.version}'
main: me.adabugra.TownyBlockBugFix.TownyBlockBugFix
api-version: '1.16'
authors: [adabugra]
description: Fixes block bug caused by TownyAdvanced
depend:
  - Towny